services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  db:
    image: mysql:5.6
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'app-datastore'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    expose:
      - "3306"

volumes:
  my-db: