spring.application.name=data-jpa-poc
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
mysql-host=${MYSQL_HOST_PARAM}